### ISSUE TITLE
GUI is horribly offset 

### ISSUE THREAD

**Issue by kurokuno** [UniversalLP/XACT#1]
GUI is horribly offset 
![2015-05-07_14 46 55](https://cloud.githubusercontent.com/assets/2988818/7508717/abb2a576-f4c8-11e4-9158-c0dec224fc89.png)

my mouse is over where the tooltip is

**Comment by univrsal** [comment]
Ok so this seems to be a conflict with a mod. This only happened in the Infinity modpack.
Edit: Looks like it's conflicting with TiCon. I'll look into that

**Comment by univrsal** [comment]
![bildschirmfoto vom 2015-05-08 19 49 37](https://cloud.githubusercontent.com/assets/8353672/7542269/b24e4e82-f5bb-11e4-8d51-977e440b301c.png)
Heey, I finally did it. This took way longer than it should've but I think the gui won't be offset now.
I won't make a release right away because I want to fix the way XACT searches for Inventories. Right now it'll basically cause dupe bugs with every non vanilla Inventory.
But if you want you can download a version with the gui fix here
https://drive.google.com/open?id=0B2Xx16RPrU-ITzNOOGY1MFdSSHc&authuser=0
