### ISSUE TITLE
Items disapearing from the crafter

### ISSUE THREAD

**Issue by JasonMcRay** [UniversalLP/XACT#10]
Quite a lot of ppl playing my modpack experienced this. It is probably after xact update to the latest, all items inside crafter are gone (both inside storage and the chips with recipes inside the crafter)

**Comment by univrsal** [comment]
So it happens when they update? From the last release to the current? Or when leaving and rejoining a world?

**Comment by JasonMcRay** [comment]
It happend after update from 0.5.3 to 0.5.4. But it did not happend to me, in my world, so I cant recreate it :(

Edit: Oh ok... it happend to me as well... i updated Xact and booom, all my items from XACT crafter gone

**Comment by JasonMcRay** [comment]
Ok sorry... I was bit confused about what are ppl trying to say to me... It seems it is happening on its own with latest XACT.

So its not just the update, its actually dissapearing after server/client/chunk unload.

**Comment by univrsal** [comment]
Oh wow, that is... I don't know how I didn't notice that... That really sucks.

It seems like the items don't randomly disappear the whole inventory just doesn't get saved.
I'll look into it now and hopefully get it fixed immediately

Edit:
Ok this is weird. This bug doesn't occur in my dev environment..
Well building the mod again seems to fix that issue for me. I have no idea what the problem was but I tested it several times now with leaving and joining a world and unloading chunks and it seems to work.
Please let me know if [this](https://github.com/UniversalLP/XACT/releases/tag/v0.5.4) release works for you aswell.

**Comment by JasonMcRay** [comment]
Will test it out probably later this week. If I will not reply in here until Sunday, feel free to Ping/Mention me, to remind it to me (i quite often forget even what i had for a lunch the same day) :D

**Comment by JasonMcRay** [comment]
@UniversalLP
Tested:
Items again gone :(

http://pastebin.com/cKmj9NYS Appeared in the log after server world loaded

**Comment by univrsal** [comment]
Well that would've been too easy...
I found out that it is an issue with saving the recipe chips I'll see what it is
Alrighty that should be fixed. It tried to do stuff with the chips before they were loaded which stopped the complete loading process.
Just download the latest release again. It contains the changes

**Comment by JasonMcRay** [comment]
OK this time no error in the server console.
Loaded backup of my world, where I had items inside the XACT crafter and..... they are all in....

So I would say: Fixed, thank you very much for being so quick :)

**Comment by univrsal** [comment]
No problem^^
