### ISSUE TITLE
[SERIOUS] Crafter dupe bug

### ISSUE THREAD

**Issue by JasonMcRay** [UniversalLP/XACT#11]
Got a report from one of players of my modpack that they managed to craft certain items without ingredients being consumed (just like it is in creatiive), when items/materials are present in the nearby container. It was tested in Singleplayer Survival.

Test has been done with IC2 Safe as the "nearby container" and I expect that probably Filling Cabinet from ExU might have the same problem. i see Xhamolk encountered same/similiar problem long time ago: https://github.com/Xhamolk/XACT/issues/91

**Comment by univrsal** [comment]
Well as a temporary fix you might wanna blacklist the IC2 save in the config.
Technically I also already blacklisted it in the code. But whatever happend to that.
I don't have any time until friday so if you really need it fixed now just replace this with the old customization part.

```
customization {
    # Make the crafter ignore blocks [default: []]
    S:ignoredBlocks <
        IC2:blockPersonal:-1
     >
}
```

**Comment by univrsal** [comment]
Ok looks like both the reported issues are fixed. I hope to release that tomorrow.
If possible it will include the adjacent crafter stuff

**Comment by 4rz0** [comment]
Does this fix apply to Carpenter's Safe as well?
I remember the dupe bug existing for it as well.

**Comment by univrsal** [comment]
Yeah, but the Carpenters safe dupe was fixed when I first heard about the issue. The IC2 safe somehow wasn't fixed back then.
Since school is keeping me busy I'll put out this pre-release now with the fixes:
[v0.5.4c](https://github.com/UniversalLP/XACT/releases/tag/v0.5.4c)
(And yes I know the gui for naming a crafter is missing the texture)

(Also the filing cabinet works just fine)

**Comment by 4rz0** [comment]
Very good to hear that, thanks for keeping this mod alive!
