### ISSUE TITLE
Oredictionary problem in XACT Craft

### ISSUE THREAD

**Issue by JasonMcRay** [UniversalLP/XACT#12]
Long time no see :) But unfortunately I have just found another bug.

You cant craft items when the recipe has multiple (2 or more) items with same oredictionary tag.
For example dyes. All the dyes I have registered under <ore:dye> (so I can easily in some recipes have it like anyDye) and their own oredict group (like <ore:dyeWhite>). But when I want to craft something that has more dyes in the recipe, XACT craft just gets confused and will tell me for example that I am missing Red Dye when I have Red Dye.

Couple Screenshot of example recipe (Lapis + Red Dye = Lime Dye) to understand better:
![2015-12-05_00 08 10](https://cloud.githubusercontent.com/assets/4236895/11603867/f5abc27a-9ae5-11e5-8336-4003a8050da6.png)

Explanation from the left:
1) 1 Lapis Lazuli => XACT crafter detects it as Red Dye
2) 2 Lapis Lazuli => XACT crafter detects it as Red Dye and Lapis, but of course the recipe dissapears because you cant craft it
3) 1 Lapis + 1 Rose Red => XACT crafter detects only the Red Dye
4) 2 Lapis + 1 Rose Red (Doesnt work with 2 Red + 1 Lapis with same recipe layout) => XACT crafter detects it correctly and its possible to craft it. Also it consumes the correct items just fine.
5) 2 Rose Red + 1 Lapis (Doesnt work with 1 Red + 2 Lapis with same recipe layout) => XACT crafter detects it correctly and its possible to craft it. Also it consumes the correct items just fine.

Difference between 4 and 5 is the recipe layout.

**Comment by univrsal** [comment]
Okay. Well as you can see right now I'm not actively working on this, but I'll definitely look into it.
Maybe I'll actually get to finish that naming idea and fix the other bugs.
~~As of now I can't access the IC Experimental jenkins, since it's down so I can't get my hands on IndustrialCraft~~
Well I got IC2, I'll see when I have time to look at it.

**Comment by univrsal** [comment]
Should be fixed with [this](https://github.com/UniversalLP/XACT/releases/tag/v0.5.5) release. 
Just tell me if you come across anything that I broke on the way^^

(Also that issue with the items not disappearing on the client side, that is still not fixed. I guess that bug will still haunt me in my dreams...)
