### ISSUE TITLE
[Suggestion] Improving Playstyle

### ISSUE THREAD

**Issue by accessdenied0** [UniversalLP/XACT#2]
Dear @UniversalLP, 

I'm aware of the fact that it is very strange in this early stage to make suggestions... But I thought I need to.

First, I want thank you for continuing this awesome mod. I missed it a lot in the last month.

Second, I just want to ask what I already have mentioned in the forum: Is it possible to add a "x" Button to clear the crafting-grid? And/or add "<" ">" button instead of having Keybindings? You surely know, today every single mod added those and It isn't surprisingly that you quickly run out of these. In addition I think it is quite more convenient for an user to press a GUI-Button instead a Key...

But... these are just suggestions... I hope you like them,

access_denied

**Comment by univrsal** [comment]
![bildschirmfoto vom 2015-05-19 16 09 55](https://cloud.githubusercontent.com/assets/8353672/7704924/8cbdc966-fe41-11e4-96d5-10b4296f1e07.png)
There you go. It's a little cramped since there's not a lot of space on the gui left.
I'm not completely happy how I've implemented it but it works.
I'll make a release of this soon.
Btw these buttons and the clear/save chip buttons now also have tooltips

**Comment by accessdenied0** [comment]
Dear @UniversalLP,

I thank you so much for noticing my suggestion... further more I'm happily surprised that you already implemented and like the idea of it. You're doing a great job.

access_denied
